fundle plugin 'oh-my-fish/theme-bobthefish'
fundle plugin 'jethrokuan/fzf'
#fundle plugin 'patrickf3139/fzf.fish'
fundle plugin 'edc/bass'
fundle plugin 'FabioAntunes/fish-nvm'
fundle plugin 'nickeb96/puffer-fish'
fundle plugin 'wfxr/forgit'

fundle init

alias ls='lsd'
alias l='ls -a'
alias c='clear'
#alias rm='echo "use trash-put"'
alias tp='trash-put'
alias cfish='vim $HOME/.config/fish/config.fish'
alias rfish='exec fish'
alias python='python3'
alias py='python'
alias pip='pip3'
